// import {
//   dairyMilk,
//   fruit1,
//   fruit2,
//   fruit3,
//   fruit4,
//   fruit5,
//   fruit6,
//   fruit7,
//   fruit8,
//   fruit9,
//   ghee1,
//   ghee2,
//   ghee3,
//   ghee4,
//   ghee5,
//   ghee6,
//   ghee7,
//   ghee8,
//   greenVagitable,
//   tea1,
//   tea2,
//   tea3,
//   tea4,
//   tea5,
//   tea6,
//   tea7,
//   tea8,
//   vagitable1,
// } from "../../../../public/image";

// const products = [
//   {
//     id: 1,
//     name: "Fresh Apples",
//     price: 120,
//     image: fruit9,
//   },
//   {
//     id: 2,
//     name: "Organic Tomato",
//     price: 600,
//     image: vagitable1,
//   },
//   {
//     id: 3,
//     name: "Milk Pack",
//     price: 350,
//     image: dairyMilk,
//   },
//   {
//     id: 4,
//     name: "Green Vegetables",
//     price: 90,
//     image: greenVagitable,
//   },

//   {
//     id: 5,
//     image: fruit1,
//     name: "Sweet Corn",
//     tittle: "freesh Sweet Corn",
//     rating: 4.2,
//     price: 16,
//   },
//   {
//     id: 6,
//     image: fruit2,
//     name: "fresho! Mushrooms",
//     tittle: "freesh fresho! Mushrooms",
//     rating: 5,
//     price: 18,
//   },
//   {
//     id: 7,
//     image: fruit3,
//     name: "Broccoli",
//     tittle: "freesh Broccoli",
//     rating: 4.7,
//     price: 17,
//   },
//   {
//     id: 8,
//     image: fruit4,
//     name: "Avocado",
//     tittle: "freesh Avocado",
//     rating: 4.1,
//     price: 14,
//   },
//   {
//     id: 9,
//     image: fruit5,
//     name: "Blueberry",
//     tittle: "freesh Blueberry",
//     rating: 4.5,
//     price: 11,
//   },
//   {
//     id: 10,
//     image: fruit6,
//     name: "Indian Blueberry",
//     tittle: "freesh Indian Blueberry",
//     rating: 5,
//     price: 20,
//   },
//   {
//     id: 11,
//     image: fruit7,
//     name: "Dragon Fruit",
//     tittle: "freesh Dragon Fruit",
//     rating: 4.3,
//     price: 12,
//   },
//   {
//     id: 12,
//     image: fruit8,
//     name: "Thai Guava",
//     tittle: "freesh Thai Guava",
//     rating: 5,
//     price: 15,
//   },
//   {
//     id: 13,
//     image: tea1,
//     name: "Red Label",
//     tittle: "Natural Care Masala Hot Tea, 1 kg",
//     rating: 4.2,
//     price: 16,
//   },
//   {
//     id: 14,
//     image: tea2,
//     name: "emperia",
//     tittle: "Kadak Tea, 2x1 kg (Multipack)",
//     rating: 5,
//     price: 18,
//   },
//   {
//     id: 15,
//     image: tea3,
//     name: "Brooke Bond Tea",
//     tittle: "Brooke Bond Tea 500gm Carton",
//     rating: 4.7,
//     price: 17,
//   },
//   {
//     id: 16,
//     image: tea4,
//     name: "Tata Tea Gold",
//     tittle: "Tea With Gently Rolled Long Leaves",
//     rating: 4.1,
//     price: 14,
//   },
//   {
//     id: 17,
//     image: tea5,
//     name: "Taj Mahal",
//     tittle: "Rich And Flavourful Tea, 500 gm",
//     rating: 4.5,
//     price: 11,
//   },
//   {
//     id: 18,
//     image: tea6,
//     name: "Organic India Tea",
//     tittle: "Organic India Tulsi Green Tea, 50gm",
//     rating: 5,
//     price: 20,
//   },
//   {
//     id: 19,
//     image: tea7,
//     name: "3 Roses Dust Tea",
//     tittle: "3 Roses Dust Green Tea, 500 g",
//     rating: 4.3,
//     price: 12,
//   },
//   {
//     id: 20,
//     image: tea8,
//     name: "Wagh Bakri",
//     tittle: "Wagh Bakri Premium Leaf Tea, 1 kg",
//     rating: 5,
//     price: 15,
//   },
//   {
//     id: 21,
//     image: ghee1,
//     name: "Nandini Ghee",
//     tittle: "Nandini Pure Ghee/Tuppa, 1 L Pouch",
//     rating: 4.2,
//     price: 16,
//   },
//   {
//     id: 22,
//     image: ghee2,
//     name: "Akshayakalpa Ghee",
//     tittle: "Akshayakalpa Organic Cow Ghee/Tuppa, 490 ml",
//     rating: 5,
//     price: 18,
//   },
//   {
//     id: 23,
//     image: ghee3,
//     name: "GRB Ghee",
//     tittle: "GRB Ghee/Tuppa, 500 ml Bottle",
//     rating: 4.7,
//     price: 17,
//   },
//   {
//     id: 24,
//     image: ghee4,
//     name: "Amul Ghee",
//     tittle: "Amul High Aroma Cow Ghee/Tuppa, 500 ml Jar",
//     rating: 4.1,
//     price: 14,
//   },
//   {
//     id: 25,
//     image: ghee5,
//     name: "Patanjali Cow Ghee",
//     tittle: "Patanjali Cow Ghee",
//     rating: 4.5,
//     price: 11,
//   },
//   {
//     id: 26,
//     image: ghee6,
//     name: "Amul Tuppa Ghee",
//     tittle: "Amul Ghee/Tuppa, 500 ml Pouch",
//     rating: 5,
//     price: 20,
//   },
//   {
//     id: 27,
//     image: ghee7,
//     name: "Desi Cow Ghee",
//     tittle: "Barosi A2 Desi Cow Ghee, 1 L",
//     rating: 4.3,
//     price: 12,
//   },
//   {
//     id: 28,
//     image: ghee8,
//     name: "Amul Pure Ghee",
//     tittle: "Amul Pure Ghee/Tuppa, 1 L Carton",
//     rating: 5,
//     price: 15,
//   },
// ];
// let fruitList = [
//   {
//     id: 1,
//     img: fruit1,
//     name: "Sweet Corn",
//     tittle: "freesh Sweet Corn",
//     rating: 4.2,
//     price: 16,
//   },
//   {
//     id: 2,
//     img: fruit2,
//     name: "fresho! Mushrooms",
//     tittle: "freesh fresho! Mushrooms",
//     rating: 5,
//     price: 18,
//   },
//   {
//     id: 3,
//     img: fruit3,
//     name: "Broccoli",
//     tittle: "freesh Broccoli",
//     rating: 4.7,
//     price: 17,
//   },
//   {
//     id: 4,
//     img: fruit4,
//     name: "Avocado",
//     tittle: "freesh Avocado",
//     rating: 4.1,
//     price: 14,
//   },
//   {
//     id: 5,
//     img: fruit5,
//     name: "Blueberry",
//     tittle: "freesh Blueberry",
//     rating: 4.5,
//     price: 11,
//   },
//   {
//     id: 6,
//     img: fruit6,
//     name: "Indian Blueberry",
//     tittle: "freesh Indian Blueberry",
//     rating: 5,
//     price: 20,
//   },
//   {
//     id: 7,
//     img: fruit7,
//     name: "Dragon Fruit",
//     tittle: "freesh Dragon Fruit",
//     rating: 4.3,
//     price: 12,
//   },
//   {
//     id: 8,
//     img: fruit8,
//     name: "Thai Guava",
//     tittle: "freesh Thai Guava",
//     rating: 5,
//     price: 15,
//   },
// ];
// let GheeList = [
//   {
//     id: 1,
//     img: ghee1,
//     name: "Nandini Ghee",
//     tittle: "Nandini Pure Ghee/Tuppa, 1 L Pouch",
//     rating: 4.2,
//     price: 16,
//   },
//   {
//     id: 2,
//     img: ghee2,
//     name: "Akshayakalpa Ghee",
//     tittle: "Akshayakalpa Organic Cow Ghee/Tuppa, 490 ml",
//     rating: 5,
//     price: 18,
//   },
//   {
//     id: 3,
//     img: ghee3,
//     name: "GRB Ghee",
//     tittle: "GRB Ghee/Tuppa, 500 ml Bottle",
//     rating: 4.7,
//     price: 17,
//   },
//   {
//     id: 4,
//     img: ghee4,
//     name: "Amul Ghee",
//     tittle: "Amul High Aroma Cow Ghee/Tuppa, 500 ml Jar",
//     rating: 4.1,
//     price: 14,
//   },
//   {
//     id: 5,
//     img: ghee5,
//     name: "Patanjali Cow Ghee",
//     tittle: "Patanjali Cow Ghee",
//     rating: 4.5,
//     price: 11,
//   },
//   {
//     id: 6,
//     img: ghee6,
//     name: "Amul Tuppa Ghee",
//     tittle: "Amul Ghee/Tuppa, 500 ml Pouch",
//     rating: 5,
//     price: 20,
//   },
//   {
//     id: 7,
//     img: ghee7,
//     name: "Desi Cow Ghee",
//     tittle: "Barosi A2 Desi Cow Ghee, 1 L",
//     rating: 4.3,
//     price: 12,
//   },
//   {
//     id: 8,
//     img: ghee8,
//     name: "Amul Pure Ghee",
//     tittle: "Amul Pure Ghee/Tuppa, 1 L Carton",
//     rating: 5,
//     price: 15,
//   },
// ];
// let TeaList = [
//   {
//     id: 1,
//     img: tea1,
//     name: "Red Label",
//     tittle: "Natural Care Masala Hot Tea, 1 kg",
//     rating: 4.2,
//     price: 16,
//   },
//   {
//     id: 2,
//     img: tea2,
//     name: "emperia",
//     tittle: "Kadak Tea, 2x1 kg (Multipack)",
//     rating: 5,
//     price: 18,
//   },
//   {
//     id: 3,
//     img: tea3,
//     name: "Brooke Bond Tea",
//     tittle: "Brooke Bond Tea 500gm Carton",
//     rating: 4.7,
//     price: 17,
//   },
//   {
//     id: 4,
//     img: tea4,
//     name: "Tata Tea Gold",
//     tittle: "Tea With Gently Rolled Long Leaves",
//     rating: 4.1,
//     price: 14,
//   },
//   {
//     id: 5,
//     img: tea5,
//     name: "Taj Mahal",
//     tittle: "Rich And Flavourful Tea, 500 gm",
//     rating: 4.5,
//     price: 11,
//   },
//   {
//     id: 6,
//     img: tea6,
//     name: "Organic India Tea",
//     tittle: "Organic India Tulsi Green Tea, 50gm",
//     rating: 5,
//     price: 20,
//   },
//   {
//     id: 7,
//     img: tea7,
//     name: "3 Roses Dust Tea",
//     tittle: "3 Roses Dust Green Tea, 500 g",
//     rating: 4.3,
//     price: 12,
//   },
//   {
//     id: 8,
//     img: tea8,
//     name: "Wagh Bakri",
//     tittle: "Wagh Bakri Premium Leaf Tea, 1 kg",
//     rating: 5,
//     price: 15,
//   },
// ];

// localStorage.setItem("allProducts", JSON.stringify(products));
// export { products, fruitList, GheeList, TeaList };
